### ISSUE TITLE
PHP Warning occur when an exception is thrown inside a stage process

### ISSUE THREAD

**Issue by enpatrik** [frankdejonge/pipeline#10]
When an exception is thrown inside a stage process this causes a warning from array_reduce. 
_"Warning: array_reduce(): An error occurred while invoking the reduction callback in ..."_

For instance, the following example (taken from the Readme):

``` php
$pipeline = (new Pipeline)
    ->pipe(CallableStage::forCallable(function () {
        throw new LogicException();
    }));

try {
    $pipeline->process($payload);
} catch(LogicException $e) {
    // Handle the exception.
}
```

^ Results in a Warning being thrown:
_Warning: array_reduce(): An error occurred while invoking the reduction callback in /var/www/pipeline/src/Pipeline.php on line 52_

I found a PHP bug ticket that seems to be related to this: https://bugs.php.net/bug.php?id=55416 that appear to be fixed in PHP 7, I tested it with 3v4l.org: https://3v4l.org/amBuY

Would it be possible to change from array_reduce and use a for loop or something else in the pipeline process to avoid getting these warnings?

**Comment by akbardhedhi** [comment]
+1, Facing the same issue on PHP 5.5.30
