### ISSUE TITLE
Adding validation of payload

### ISSUE THREAD

**Issue by RonRademaker** [frankdejonge/pipeline#14]
Hi, 

I noticed I start pretty much any stageinterface I create with the same bits of code:

```
public function process($payload)
{
    if ($this->isValidPayload($payload)) {
        // the actual code
    }

    throw new InvalidPayloadException('Payload must be a ...');
}

 /**
  * Checks if the payload is valid
  */
private function isValidPayload($payload)
{
    // logic to check if payload is an array, instanceof something or whatever
}
```

If this is common I'd create a PR to have an abstract stageinterface providing this base functionality. Let me know if this is something you think is valuable for the project.

Regards,
Ron

**Comment by frankdejonge** [comment]
@RonRademaker you can just use a stage for this, the exception will break the execution chain.
