### ISSUE TITLE
Adding short circuiting mechanism

### ISSUE THREAD

**Issue by marcosh** [frankdejonge/pipeline#16]
Hi,

I think it would be nice to have a short circuiting mechanism that would allow to skip the following stages.

This would allow to decide at runtime when to stop with the pipeline processing. It would be a more general approach than #13 

I am thinking to something along these lines:
- add an optional parameter to the `Pipeline` constructor

```
public function __construct(array $stages = [], callable $shortCircuiting = null)
```
- add a check in the `process` method

```
foreach ($this->stages as $stage) {
    $payload = $reducer($payload, $stage);
    if ($this->shortCircuiting($payload)) {
        continue;
    }
}
```

What do you think? Could it be something useful?

**Comment by frankdejonge** [comment]
@marcosh recently implemented in the InterruptibleProcessor.
