### ISSUE TITLE
Pipeline should use call_user_func 

### ISSUE THREAD

**Issue by nyamsprod** [frankdejonge/pipeline#17]
When porting Pipeline to League\Uri package, I came across a bug with the following code. 

``` php
    public function process($payload)
    {
        foreach ($this->stages as $stage) {
            $payload = $stage($payload);
        }
        return $payload;
    }
```

As it turned there's a [PHP bug entry](https://bugs.php.net/bug.php?id=68475) for that and Evert Pot wrote a [blog post](http://evertpot.com/on-callables-and-closures/) about it too :+1:  

What's sad is that it won't be correctly fix  in PHP until [this RFC passes](https://wiki.php.net/rfc/consistent_callables) :-1: . 

So the current workaround is to use `call_user_func` or `call_user_func_array` instead like this:

``` php
    public function process($payload)
    {
        foreach ($this->stages as $stage) {
            $payload = call_user_func($stage, $payload);
        }
        return $payload;
    }
```

**Comment by nyamsprod** [comment]
great :+1:

**Comment by frankdejonge** [comment]
@nyamsprod didn't have notifications on for this repo, sorry for the delay. You can ping me when this happens :neckbeard:
