### ISSUE TITLE
Never heard of a pattern named pipeline

### ISSUE THREAD

**Issue by cmyker** [frankdejonge/pipeline#32]
Is there any proof links to the publications of a famous OOP evangelists?

**Comment by colinodell** [comment]
A quick search for "pipeline pattern" on Google returns millions of results, including this one by Martin Fowler: https://martinfowler.com/articles/collection-pipeline/

**Comment by GrahamCampbell** [comment]
> Is there any proof

This not a theorem, rather, it is a definition. There is no proof, with respect to any system.
