### ISSUE TITLE
[Feature Request] Attach a listener to a pipeline

### ISSUE THREAD

**Issue by alexandrubeu** [frankdejonge/pipeline#37]
The concept of a pipe sounds very good but I was wondering if we can attach listeners for each stage

For example, we can have like PielineListenerInteface

```
interface PipelineListenerInterface
{
    function before($context, $stageName);

    function onError($context, $stageName, $exception);
}
```
Then we can easily log all the stages instead of catching all the pipelines.

It will be very cool if we can register the listener on project level (not on a pipeline).

**Comment by alexandrubeu** [comment]
If it sounds interesting maybe I can help out with the implementation.

**Comment by shadowhand** [comment]
I think this would be better served by placing an event dispatcher into stages that need listeners. Or using an observable.
