### ISSUE TITLE
When to use a PipelineBuilder?

### ISSUE THREAD

**Issue by alexandrubau** [frankdejonge/pipeline#47]
Hi guys, can anyone please help me a little bit?

I can't get my head around the PipelineBuilder class. I don't understand when I should use it?
The Pipeline object itself can be extended and reused at anytime, so I don't quite understand when I should use the Pipeline or the PipelineBuilder.

Thanks for your help!

**Comment by vidalvasconcelos** [comment]
@alexandrubau  I imagine there are some contexts when the pipeline stack is used as a bag, in this case, will be more easily work with the builder instead of the object.
