### ISSUE TITLE
Simple question

### ISSUE THREAD

**Issue by redeemefy** [frankdejonge/pipeline#49]
What are you using to generate compile your `docs`?

**Comment by shadowhand** [comment]
League uses [Github Pages](https://pages.github.com/).

**Comment by redeemefy** [comment]
Do you have tutorials or know any resources to learn how to use the tools? The page has only an example.

**Comment by shadowhand** [comment]
https://help.github.com/categories/github-pages-basics/

**Comment by redeemefy** [comment]
I'm asking training tutorial about pipeline rather. Sorry about the confusion.

**Comment by shadowhand** [comment]
Pipeline is a very small package. I would hope that the examples provided are enough to get you started. If not, there are tutorials available online with a search.

**Comment by redeemefy** [comment]
Fare enough.
