### ISSUE TITLE
windows is ok?

### ISSUE THREAD

**Issue by 54huige** [frankdejonge/pipeline#50]
windows is ok?

**Comment by shadowhand** [comment]
If you are asking "does Pipeline work on Windows?" the answer is:

Pipeline uses PHP and runs anywhere that PHP can run.

**Comment by 54huige** [comment]
是的 这太好了 ，非常感谢

**Comment by 54huige** [comment]
> 如果你问“管道在Windows上工作吗？” 答案是：
> 
> Pipeline使用PHP并运行PHP可以运行的任何地方。

是的 这太好了 ，非常感谢
