### ISSUE TITLE
PipelineBuilder build returns PipelineBuilderInterface in error

### ISSUE THREAD

**Issue by jwhulette** [frankdejonge/pipeline#52]
In the PipelineBuilder.php, the build method says it returns an PipelineBuilderInterface, when it actually returns a Pipeline.

**Comment by jdreesen** [comment]
No, the `PipelineBuilder::build()` method says it returns a `PipelineInterface` which is implemented by the returned `Pipeline` class. So everything's fine.

**Comment by jwhulette** [comment]
I'm an idiot... My apologies. This is what happens when you have fried your brain from doing PL/SQL all day.
