### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by r4j4h** [frankdejonge/pipeline#6]
Hello,

I am curious of how pipeline suggests we handle errors in our processors? I think the documentation should cover this case, even if it's just "wrap your calls to the pipeline in your own try/catches" :)

**Comment by frankdejonge** [comment]
@r4j4h this package is completely transparent about this, stages should handle exception internally and if not the consumer of the pipeline should be aware that exception will bubble up if not dealt with. It's a per-case decision really. If pipeline would formalise, this it would only be limiting.

**Comment by colinodell** [comment]
That methodology makes sense to me.  I do agree with @r4j4h that perhaps it should be mentioned in the docs/README somewhere, as I can see this being a common question.

**Comment by frankdejonge** [comment]
@r4j4h @colinodell I've added a note in the documentation about this: http://pipeline.thephpleague.com/usage/#exception-handling

**Comment by r4j4h** [comment]
Perfect! Thanks so much you two :)
