### ISSUE TITLE
PHP 5.4 compatibility

### ISSUE THREAD

**Issue by RonRademaker** [frankdejonge/pipeline#8]
Hi,

I'm currently stuck on PHP 5.4 and wanted to use this package. The changes to make the package PHP 5.4 compatible were quite trivial, if you want to support 5.4 I can wrap up a PR if you like. If not, I understand as PHP 5.4 is near EOL.

**Comment by GrahamCampbell** [comment]
:-1: for supporting 5.4, sorry.

**Comment by jamesdb** [comment]
From what i can see [StageInterface::class](https://github.com/thephpleague/pipeline/blob/master/src/Pipeline.php#L25) is the only thing stopping this from working on 5.4.

For the sake of such a small change i think it should be considered.

**Comment by RonRademaker** [comment]
Hi @jamesdb ,

There are a few usages of ::class in the tests as well (see https://github.com/RonRademaker/pipeline/commit/558157133618e435b0808fa96275789a90308b93)

**Comment by GrahamCampbell** [comment]
I don't think it should be changed anyway. PHP 5.4 is end of life VERY soon.

**Comment by frankdejonge** [comment]
@RonRademaker what you "could" do, it install the packages while ignoring platform restrictions, detail about this are in the composer documentations. Since it's 12 days away from not even receiving security updates I'm not lowering the minimum version as that sends the wrong message imo.
